import type { MenuItem, MenuCategory } from './menu';

export const MOCK_CATEGORIES: MenuCategory[] = [
  {
    id: 'cat-1',
    restaurantId: 'res-1',
    name: 'Signature Burgers',
    description: 'Our world-famous handcrafted burgers',
    displayOrder: 1,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-2',
    restaurantId: 'res-1',
    name: 'Appetizers',
    description: 'Perfect for sharing',
    displayOrder: 2,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-3',
    restaurantId: 'res-1',
    name: 'Drinks',
    description: 'Refreshing beverages',
    displayOrder: 3,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-4',
    restaurantId: 'res-1',
    name: 'Fresh Salads',
    description: 'Healthy and vibrant greens',
    displayOrder: 4,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-5',
    restaurantId: 'res-1',
    name: 'Italian Pasta',
    description: 'Authentic handmade pasta dishes',
    displayOrder: 5,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-6',
    restaurantId: 'res-1',
    name: 'Sweet Desserts',
    description: 'The perfect ending to your meal',
    displayOrder: 6,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_ITEMS: MenuItem[] = [
  {
    id: 'item-1',
    restaurantId: 'res-1',
    categoryId: 'cat-1',
    name: 'Wagyu Signature Burger',
    price: 305000,
    description: 'Premium Wagyu beef patty, truffle aioli, caramelized onions, and aged cheddar on a brioche bun.',
    prepTimeMinutes: 15,
    status: 'available',
    isChefRecommended: true,
    isDeleted: false,
    popularityScore: 98,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    canOrder: true,
    calories: 850,
    ingredients: ['Wagyu Beef', 'Brioche Bun', 'Truffle Aioli', 'Caramelized Onions', 'Aged Cheddar'],
    allergens: ['Dairy', 'Gluten', 'Eggs'],
    chefNote: 'The truffle aioli is made fresh daily using black winter truffles. I recommend medium-rare for the best experience.',
    primaryPhoto: {
      id: 'photo-1',
      menuItemId: 'item-1',
      url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop',
      isPrimary: true,
      createdAt: new Date().toISOString(),
    },
    modifierGroups: [
      {
        id: 'mod-1',
        restaurantId: 'res-1',
        name: 'Doneness',
        selectionType: 'single',
        isRequired: true,
        minSelections: 1,
        maxSelections: 1,
        displayOrder: 1,
        status: 'active',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        options: [
          { id: 'opt-1', groupId: 'mod-1', name: 'Medium Rare', priceAdjustment: 0, status: 'active', createdAt: new Date().toISOString() },
          { id: 'opt-2', groupId: 'mod-1', name: 'Medium', priceAdjustment: 0, status: 'active', createdAt: new Date().toISOString() },
          { id: 'opt-3', groupId: 'mod-1', name: 'Well Done', priceAdjustment: 0, status: 'active', createdAt: new Date().toISOString() },
        ],
      },
      {
        id: 'mod-2',
        restaurantId: 'res-1',
        name: 'Extra Toppings',
        selectionType: 'multiple',
        isRequired: false,
        minSelections: 0,
        maxSelections: 3,
        displayOrder: 2,
        status: 'active',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        options: [
          { id: 'opt-4', groupId: 'mod-2', name: 'Extra Bacon', priceAdjustment: 45000, status: 'active', createdAt: new Date().toISOString() },
          { id: 'opt-5', groupId: 'mod-2', name: 'Avocado', priceAdjustment: 30000, status: 'active', createdAt: new Date().toISOString() },
          { id: 'opt-6', groupId: 'mod-2', name: 'Fried Egg', priceAdjustment: 20000, status: 'active', createdAt: new Date().toISOString() },
        ],
      },
    ],
  },
  {
    id: 'item-2',
    restaurantId: 'res-1',
    categoryId: 'cat-1',
    name: 'Classic Cheeseburger',
    price: 185000,
    description: 'Angus beef, lettuce, tomato, pickles, and our secret house sauce.',
    prepTimeMinutes: 10,
    status: 'available',
    isChefRecommended: false,
    isDeleted: false,
    popularityScore: 85,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    canOrder: true,
    calories: 650,
    ingredients: ['Angus Beef', 'Sesame Bun', 'Cheddar Cheese', 'Lettuce', 'Tomato', 'House Sauce'],
    allergens: ['Dairy', 'Gluten', 'Mustard'],
    primaryPhoto: {
      id: 'photo-2',
      menuItemId: 'item-2',
      url: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?q=80&w=800&auto=format&fit=crop',
      isPrimary: true,
      createdAt: new Date().toISOString(),
    },
    modifierGroups: [],
  },
  {
    id: 'item-3',
    restaurantId: 'res-1',
    categoryId: 'cat-2',
    name: 'Truffle Fries',
    price: 95000,
    description: 'Crispy golden fries tossed in white truffle oil and parmesan cheese.',
    prepTimeMinutes: 8,
    status: 'available',
    isChefRecommended: true,
    isDeleted: false,
    popularityScore: 92,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    canOrder: true,
    calories: 420,
    ingredients: ['Potato', 'Truffle Oil', 'Parmesan', 'Parsley'],
    allergens: ['Dairy'],
    primaryPhoto: {
      id: 'photo-3',
      menuItemId: 'item-3',
      url: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?q=80&w=800&auto=format&fit=crop',
      isPrimary: true,
      createdAt: new Date().toISOString(),
    },
    modifierGroups: [],
  },
  {
    id: 'item-11',
    restaurantId: 'res-1',
    categoryId: 'cat-2',
    name: 'Buffalo Wings',
    price: 145000,
    description: 'Spicy buffalo chicken wings served with blue cheese dip and celery.',
    prepTimeMinutes: 12,
    status: 'available',
    isChefRecommended: false,
    isDeleted: false,
    popularityScore: 88,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    canOrder: true,
    calories: 580,
    ingredients: ['Chicken Wings', 'Buffalo Sauce', 'Blue Cheese', 'Celery'],
    allergens: ['Dairy', 'Gluten'],
    primaryPhoto: {
      id: 'photo-11',
      menuItemId: 'item-11',
      url: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?q=80&w=800&auto=format&fit=crop',
      isPrimary: true,
      createdAt: new Date().toISOString(),
    },
    modifierGroups: [],
  },
  {
    id: 'item-5',
    restaurantId: 'res-1',
    categoryId: 'cat-4',
    name: 'Classic Caesar Salad',
    price: 125000,
    description: 'Romaine lettuce, parmesan cheese, croutons, and our house-made Caesar dressing.',
    prepTimeMinutes: 7,
    status: 'available',
    isChefRecommended: false,
    isDeleted: false,
    popularityScore: 82,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    canOrder: true,
    calories: 320,
    ingredients: ['Romaine Lettuce', 'Parmesan', 'Croutons', 'Caesar Dressing'],
    allergens: ['Dairy', 'Gluten', 'Fish'],
    primaryPhoto: {
      id: 'photo-5',
      menuItemId: 'item-5',
      url: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?q=80&w=800&auto=format&fit=crop',
      isPrimary: true,
      createdAt: new Date().toISOString(),
    },
    modifierGroups: [
      {
        id: 'mod-3',
        restaurantId: 'res-1',
        name: 'Add Protein',
        selectionType: 'single',
        isRequired: false,
        minSelections: 0,
        maxSelections: 1,
        displayOrder: 1,
        status: 'active',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        options: [
          { id: 'opt-7', groupId: 'mod-3', name: 'Grilled Chicken', priceAdjustment: 45000, status: 'active', createdAt: new Date().toISOString() },
          { id: 'opt-8', groupId: 'mod-3', name: 'Grilled Shrimp', priceAdjustment: 65000, status: 'active', createdAt: new Date().toISOString() },
          { id: 'opt-9', groupId: 'mod-3', name: 'Smoked Salmon', priceAdjustment: 75000, status: 'active', createdAt: new Date().toISOString() },
        ],
      },
    ],
  },
  {
    id: 'item-6',
    restaurantId: 'res-1',
    categoryId: 'cat-4',
    name: 'Quinoa Power Bowl',
    price: 165000,
    description: 'Organic quinoa, roasted sweet potato, avocado, kale, and lemon tahini dressing.',
    prepTimeMinutes: 10,
    status: 'available',
    isChefRecommended: true,
    isDeleted: false,
    popularityScore: 90,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    canOrder: true,
    calories: 480,
    ingredients: ['Quinoa', 'Sweet Potato', 'Avocado', 'Kale', 'Tahini'],
    allergens: ['Sesame'],
    chefNote: 'A perfect balance of protein and healthy fats. Great for a light yet filling lunch.',
    primaryPhoto: {
      id: 'photo-6',
      menuItemId: 'item-6',
      url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop',
      isPrimary: true,
      createdAt: new Date().toISOString(),
    },
    modifierGroups: [],
  },
  {
    id: 'item-7',
    restaurantId: 'res-1',
    categoryId: 'cat-5',
    name: 'Spaghetti Carbonara',
    price: 195000,
    description: 'Traditional Roman style with guanciale, pecorino romano, egg yolk, and black pepper.',
    prepTimeMinutes: 15,
    status: 'available',
    isChefRecommended: true,
    isDeleted: false,
    popularityScore: 95,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    canOrder: true,
    calories: 720,
    ingredients: ['Spaghetti', 'Guanciale', 'Pecorino Romano', 'Egg Yolk', 'Black Pepper'],
    allergens: ['Dairy', 'Gluten', 'Eggs'],
    chefNote: 'We use authentic guanciale and no cream, just like in Rome.',
    primaryPhoto: {
      id: 'photo-7',
      menuItemId: 'item-7',
      url: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?q=80&w=800&auto=format&fit=crop',
      isPrimary: true,
      createdAt: new Date().toISOString(),
    },
    modifierGroups: [],
  },
  {
    id: 'item-9',
    restaurantId: 'res-1',
    categoryId: 'cat-6',
    name: 'Classic Tiramisu',
    price: 115000,
    description: 'Layers of espresso-soaked ladyfingers and creamy mascarpone cheese.',
    prepTimeMinutes: 5,
    status: 'available',
    isChefRecommended: true,
    isDeleted: false,
    popularityScore: 94,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    canOrder: true,
    calories: 450,
    ingredients: ['Mascarpone', 'Espresso', 'Ladyfingers', 'Cocoa Powder'],
    allergens: ['Dairy', 'Gluten', 'Eggs'],
    primaryPhoto: {
      id: 'photo-9',
      menuItemId: 'item-9',
      url: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?q=80&w=800&auto=format&fit=crop',
      isPrimary: true,
      createdAt: new Date().toISOString(),
    },
    modifierGroups: [],
  },
  {
    id: 'item-4',
    restaurantId: 'res-1',
    categoryId: 'cat-3',
    name: 'Iced Hibiscus Tea',
    price: 65000,
    description: 'House-brewed hibiscus tea with a hint of lime and honey.',
    prepTimeMinutes: 5,
    status: 'available',
    isChefRecommended: false,
    isDeleted: false,
    popularityScore: 78,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    canOrder: true,
    calories: 80,
    ingredients: ['Hibiscus Flowers', 'Lime', 'Honey'],
    allergens: [],
    primaryPhoto: {
      id: 'photo-4',
      menuItemId: 'item-4',
      url: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?q=80&w=800&auto=format&fit=crop',
      isPrimary: true,
      createdAt: new Date().toISOString(),
    },
    modifierGroups: [],
  },
  {
    id: 'item-12',
    restaurantId: 'res-1',
    categoryId: 'cat-3',
    name: 'Craft IPA Beer',
    price: 120000,
    description: 'Local craft IPA with citrus and pine notes.',
    prepTimeMinutes: 2,
    status: 'available',
    isChefRecommended: false,
    isDeleted: false,
    popularityScore: 84,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    canOrder: true,
    calories: 210,
    ingredients: ['Barley', 'Hops', 'Yeast', 'Water'],
    allergens: ['Gluten'],
    primaryPhoto: {
      id: 'photo-12',
      menuItemId: 'item-12',
      url: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?q=80&w=800&auto=format&fit=crop',
      isPrimary: true,
      createdAt: new Date().toISOString(),
    },
    modifierGroups: [],
  },
  {
    id: 'item-13',
    restaurantId: 'res-1',
    categoryId: 'cat-3',
    name: 'Fresh Orange Juice',
    price: 75000,
    description: '100% freshly squeezed Valencia oranges.',
    prepTimeMinutes: 5,
    status: 'available',
    isChefRecommended: false,
    isDeleted: false,
    popularityScore: 89,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    canOrder: true,
    calories: 120,
    ingredients: ['Valencia Oranges'],
    allergens: [],
    primaryPhoto: {
      id: 'photo-13',
      menuItemId: 'item-13',
      url: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?q=80&w=800&auto=format&fit=crop',
      isPrimary: true,
      createdAt: new Date().toISOString(),
    },
    modifierGroups: [],
  },
];
